name: CloudFormation Lint and Guard

on:
  workflow_dispatch:
  push:
    branches:
      - "feature/*"
      - "fix/*"

jobs:
  lint-and-guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          repository: becchi78/shared-config
          path: config
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Install cfn-guard
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh

      - name: Run cfn-lint
        run: cfn-lint template.yaml

      - name: Run cfn-guard
        run: ~/.guard/bin/cfn-guard validate -r config/CloudFormation/ruleset.guard -d template.yaml
